development:
  adapter: postgresql
  encoding: unicode
  database: imginho_development
  pool: 5
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: imginho_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV['DB_POOL'] || ENV['MAX_THREADS'] || 5 %>
  url:  <%= ENV['DATABASE_URL'] %>
